---
title: "BluPlusTags"
author: "Patrick D. lorch"
date: "2026-05-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import data

This example uses data downloaded from the blu+ portal

https://blu.ctt-iow.com/#/main

```{r data}
library(lubridate)
library(dplyr)
bluIn = "SSRS_2025-2854_detections.csv"
bluIn_deployment = "SSRS_2025-2854_deploy_info.csv"

bluplus_data = read.csv(file = file.path("data",
                                    bluIn))
bluplus_data = bluplus_data %>%
  mutate(time_utc = as_datetime(time_utc, tz = "UTC")) %>%
  select(c("source", 
           "tag_id", 
           "time_utc", 
           "lat", 
           "lon", 
           "conf", 
           "rssi"))

# Create seperate files for types of detections
bp_data_terra = bluplus_data %>%
  filter(source == "terra")

bp_data_crowd = bluplus_data %>%
  filter(source == "crowd_sourced")

# Get deployment file
bluplus_deployment = read.csv(file = file.path("data",
                                               bluIn_deployment))
bluplus_deployment = bluplus_deployment %>%
  mutate(deploy_at_utc = as_datetime(deploy_at_utc, tz = "UTC"))
bluplus_deployed = bluplus_deployment %>%
  filter(weight_grams != -1)

```

## Including Plots

Currently, slider only works for crowd sourced points.  I will split out Terra derived points once more of this is settled. 

Set up to either show a range of time points or a moving 'follow_time' number of data points.

### Time slider plot

```{r blumap}
library(dplyr)
library(leaflet)
library(leaflet.extras2)
library(sf)
library(plotrix)
library(htmltools)
library(htmlwidgets)

map_output = "maps"
# Set range_not_follow to T to have a range slider. If set F,
#  just one slider handle and it shows past 'follow_time' 
#  time-points of data.
range_not_follow =F
follow_time = 10

bp_data_terra_sf = st_as_sf(bp_data_terra, coords = c("lon", "lat"), crs = 4326)
bp_data_crowd_sf = st_as_sf(bp_data_crowd, coords = c("lon", "lat"), crs = 4326)

# Center on crowd sourced data since it is widely spread
center = st_coordinates(st_centroid(summarize(bp_data_crowd_sf)))
zoom = 8

pal_t <- colorFactor(
  palette = "magma",
  domain = bp_data_terra_sf$tag_id,
  na.color = "#737373")
pal_c <- colorFactor(
  palette = "magma",
  domain = bp_data_crowd_sf$tag_id,
  na.color = "#737373")

m = leaflet() %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles('Esri.WorldImagery', 
                   group = "Esri World Imagery") %>%
  setView(center[1], center[2], zoom) %>%
  addCircleMarkers(data = bp_data_terra_sf,
              color= ~pal_t(tag_id),
              label = ~tag_id,
              labelOptions = labelOptions(noHide = F, 
                                          textsize = "10px"),
              popup = ~htmlEscape(time_utc, 
                                            attribute = F),
              opacity = 0.8,
              group = "Terra detections") %>%
  addCircleMarkers(data = bp_data_crowd_sf,
              color= ~pal_c(tag_id),
              label = ~tag_id,
              labelOptions = labelOptions(noHide = F, 
                                          textsize = "10px"),
              popup = ~htmlEscape(time_utc, 
                                            attribute = F),
              opacity = 0.8,
              group = "Crowd-source detections") %>%
 addScaleBar(position = "bottomleft") %>%
 addLegend(data = bp_data_terra_sf,
            position = "bottomleft", 
            pal = pal_c, 
            values = ~tag_id,
            title = "Tag ID",
            opacity = 1)%>%
  addLayersControl(
    baseGroups = c("Esri World Imagery", "OSM (default)"),
    overlayGroups = c("Terra detections", 
                      "Crowd-source detections"),
    position = "bottomright",
    options = layersControlOptions(collapsed = TRUE)
    ) %>%
  # addTimeslider(data = bp_data_terra_sf,
  #   options = timesliderOptions(
  #     position = "topright",
  #     timeAttribute = "time_utc",
  #     range = TRUE
  #   )
  # ) %>%
  addTimeslider(data = bp_data_crowd_sf,
                fill = T,
    options = timesliderOptions(
      position = "topright",
      timeAttribute = "time_utc",
      range = range_not_follow,
      follow = follow_time,
      showAllOnStart = F,
      alwaysShowDate = T
    )
  ) %>%
  hideGroup(c("Terra detections"))

m

saveWidget(m, file = file.path(map_output,
                               paste0("BluPlusTags",
                                      "_", focal_id,
                                      "_", Sys.Date(),
                                      ".html")))

```

### Rate and confidence plot

```{r timeconf}


unique(bp_data_crowd_sf$tag_id)
# focal_id = "BA8E892D"
focal_id = "948743B6"
zoom2 = 9
diam_cex = 50

bp_data_crowd_sf_focal = bp_data_crowd_sf %>%
  filter(tag_id == focal_id) %>%
  arrange(time_utc) %>%
  mutate(diff_from_next = 
           c(as.numeric(difftime(time_utc, lead(time_utc), units = "sec"))),
         time_period = seconds_to_period(-as.numeric(diff_from_next)),
         time_intervals = cut(-as.numeric(diff_from_next),
                              breaks = 
                                c(0,60,
                                  c(1,2,4,6,8,10,12,24,48)*3600),
                              labels = c("Seconds",
                                         "Minutes",
                                         "1 hr",
                                         "2 hrs",
                                         "4 hrs",
                                         "6 hrs",
                                         "8 hrs",
                                         "10 hrs",
                                         "12 hrs",
                                         "1 day")))

bp_data_crowd_sf_focal_linestring = bp_data_crowd_sf_focal %>%
  summarize(do_union = F) %>%
  st_cast("LINESTRING")

center2 = st_coordinates(st_centroid(summarize(bp_data_crowd_sf_focal)))

pal_time <- colorFactor(
  palette = "RdYlBu",
  domain = bp_data_crowd_sf_focal$time_intervals,
  na.color = "#737373")

m1 = leaflet() %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles('Esri.WorldImagery', 
                   group = "Esri World Imagery") %>%
  setView(center2[1], center2[2], zoom2) %>%

  addCircleMarkers(data = bp_data_crowd_sf_focal,
              color= ~pal_time(time_intervals),
              label = ~time_utc,
              labelOptions = labelOptions(noHide = F, 
                                          textsize = "10px"),
              popup = ~htmlEscape(paste0("conf: ", 
                                        conf, ", ", 
                                        "time interval: ",
                                        time_period), 
                                            attribute = F),
              radius = ~ 1/sqrt(conf)*diam_cex,
              opacity = 0.8,
              clusterOptions = T,
              group = "Crowd-source detections") %>%
  addPolylines(data = bp_data_crowd_sf_focal_linestring) %>%
  # addPolygons(st_linestring(geometry)) %>%
  addScaleBar(position = "bottomleft") %>%
  addLegend(data = bp_data_crowd_sf_focal,
            position = "bottomleft", 
            pal = pal_time, 
            values = ~time_intervals,
            title = "Size ~ conf, color ~ residence time",
            opacity = 1)%>%
  addLayersControl(
    baseGroups = c("Esri World Imagery", "OSM (default)"),
    overlayGroups = c("Crowd-source detections"),
    position = "bottomright",
    options = layersControlOptions(collapsed = TRUE)
    )

m1

saveWidget(m1, file = file.path(map_output,
                                paste0("BluPlusTags_confidence_residence",
                                       "_", focal_id,
                                       "_", Sys.Date(),
                                       ".html")), selfcontained = T)


```

